meta_name: "FindHint"
meta_title: "FindHint - Plus ludique qu'un simple CV"
meta_description: "Plutot que de t'envoyer mon CV, je te propose de me découvrir à travers 4 petites énigmes..."
meta_image: "photo1.jpg"
twitter_account: "@no_ar35"
