meta_name: "FindHint"
meta_title: "FindHint - Plus agréable qu'un simple CV"
meta_description: "Plutot que de t'envoyer mon CV, viens voir ce dont je suis capable de façon ludique, à travers 4 petites énigmes..."
meta_image: "photo1.jpg"
twitter_account: "@no_ar35"
